### ISSUE TITLE
[Post-processing] Aggregation output seems broken 

### ISSUE THREAD

**Issue by chapuisk** [COMOKIT/COMOKIT-HPC#2]
Using output data from COMOKIT-Azure the number of susceptible at the beginning should be exactly 39335, whereas it is around 5k according to the output of comokit2png.py script.

**Comment by RoiArthurB** [comment]
cf : ![image](https://user-images.githubusercontent.com/16764085/100562650-e6c1d500-32ee-11eb-9496-4d4aca463082.png)
